### ISSUE TITLE
User.javaのpublic String getDisplayNameById(int userId)で空文字が返却されない

### ISSUE THREAD

**Issue by g031s074** [software-practice-r4/sys-practice#37]
public String getDisplayNameById(int userId)
存在しないuserIdの100を与えたとき、

エラー情報
Exception in thread "main" Closing the connection.
java.lang.NullPointerException
	at sys_practice.User.getDisplayNameById(User.java:207)
	at sys_practice.Test.main(Test.java:13)
は表示されたものの、空文字が返却されない。

テスト項目ではエラー情報の表示と空文字の返却とある

**Comment by 12h1No** [comment]
null時に空文字返却するように修正済み
